##
#
# Travis CI script for keyvi
#


language: cpp

compiler:
 - clang
 - gcc

env:
  matrix:
    - CONF=debug   ARCH=x86_64
    - CONF=release ARCH=x86_64
  global:
    - GITHUB_REPO='cliqz-oss/keyvi'

before_install:
  - if [ "$CC" = "gcc" ] && [ "$CONF" = "debug" ]; then sudo pip install cpp-coveralls; export GCOV_FLAGS='--coverage'; fi

install:
  - if [ "$CC" = "gcc" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90;fi
  - if [ "$CC" = "gcc" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90;fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - scons
    - valgrind
    - cmake
    - libboost-thread1.55-dev
    - libboost-system1.55-dev
    - libboost-test1.55-dev
    - libboost1.55-dev
    - libboost-date-time1.55-dev
    - libboost-regex1.55-dev
    - libboost-filesystem1.55-dev
    - libboost-program-options1.55-dev
    - libboost-iostreams1.55-dev
    - libsnappy-dev
    - zlib1g-dev
    - doxygen
    - libstdc++-4.8-dev

script:
  - cd keyvi
  - scons -j 2 mode=$CONF
  - $CONF/dictionaryfsa_unittests/dictionaryfsa_unittests

sudo: true
#after_success:
#  - coveralls -r .. --gcov-options '\-lp' -e thirdparty -e example -e test -e build/CMakeFiles -e include/rapidjson/msinttypes -e include/rapidjson/internal/meta.h -e include/rapidjson/error/en.h
